### ISSUE TITLE
Remove unwanted files

### ISSUE THREAD

**Issue by chandansgowda** [chandansgowda/flutter_ui_kit#16]
Hey @Moinuddin9777 
Please refactor whatever is in a separate neomorphic folder and bring it inside the main lib folder itself. I'm assigning this to you since you had worked on the same earlier.

_Originally posted by @chandansgowda in https://github.com/chandansgowda/flutter_ui_kit/pull/14#issuecomment-1284071751_

**Comment by Moinuddin9777** [comment]
@chandansgowda   
I think that will be a problem because I am using different state management(GetX) and global routes   
so there will be a merge conflict in main.dart , i
I can move the whole folder inside the main folder instead.  
.................................................................................................................................................................
Or there is another approach to do this, Let's make the whole project with GetX as state management and combine the designs on the home screen we can have tiles like this
.....................................................................................................................................................................

![image](https://user-images.githubusercontent.com/76849575/197337535-8085c12b-f761-4ae8-82ab-50670176a23d.png)

**Comment by chandansgowda** [comment]
Hey @Moinuddin9777 
We are using Providers for state management and now introducing GetX will make it difficult for other contributors to work on the project. Please remove GetX and use Providers as a replacement. You can take help from @ShivamMenda if required.
Thanks

**Comment by Moinuddin9777** [comment]
Alright, this sounds good but I'm not at all experienced with Provider...
So @ShivamMenda you can work on routes and other state management stuff while I work on UI.
I will also push the code for other apps in neumorphic theme and side by side you can work on state management

**Comment by ShivamMenda** [comment]
@Moinuddin9777 I would encourage you to read up about provider because the whole purpose of hacktoberfest is to learn new things try implementing it and open a PR. If any help or resources are required or if any merge conflicts I'll help you resolve them during the time of the PR. It would be a valuable contribution to our repo too. I wish you all the best.

**Comment by Moinuddin9777** [comment]
> Replying to @ShivamMenda 

Alright if you'll take care of merge conflicts there is no problem will soon be pushing UI of other apps too with provider

**Comment by ShivamMenda** [comment]
@Moinuddin9777 Sure will look into it. Try to avoid the conflicts as much as possible. I'll be there to help.
